name: Streams height data processing workflow

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the top of the hour
  workflow_dispatch:  # Allows for manual triggering

jobs:
  data_processing_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for the branch to allow commits
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas geopandas requests

      - name: Run Data Processing Script
        env:
          FTP_HOST: "ftp.bom.gov.au"
          FTP_DIRECTORY: "/anon/gen/fwo/"
          STATION_URL: "http://reg.bom.gov.au/catalogue/rain_river_station_list.csv"
        run: python scripts/data_process.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add datasets
          git commit -m "Update datasets with new data"
          git push origin ${{ github.ref_name }}  # Push to the same branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}